# -*- coding: utf-8 -*-
"""ModelPredictImplement.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uzc2lUbdj4AnvTJxWPJlYGF_FjeIGc9I
"""

'''
El propòsit d'aquest programari és recollir, formatar, i implementar la informació en el model de riscos recollida per l'enquesta en l'enquesta següent:
https://forms.gle/b4CpQtGzo4c74GXD7
'''

#S'importen llibreries per a accedir i modificar els documents amb les informacions
from google.colab import auth
import pandas as pd
import gspread
from google.auth import default

#s'autoritza al programari l'acces al document on està guardada les respostes dels pacients.
auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)

#S'obre el document es canvía el format per facilitar l'edició
worksheet = gc.open('Factors de Risc del Càncer de Mama (Responses)').sheet1
valors = worksheet.get_all_values()
valorsDF = pd.DataFrame(valors)
valorsDF.head()

#S'instalen i importen llibreries per importar la classe
!pip install import-ipynb
import import_ipynb

import ClasseModelGAIL

#Crea una funció que retorna els riscos amb un format agradable.
def obDadesFormat(nom, edat, etnia, menarquia, prPart, fPrimGrau, biop, hipAtip, data):
  pacient = ClasseModelGAIL.modelRiscCanMama(edat, etnia, menarquia, prPart, fPrimGrau, biop, hipAtip,data)
  #print(pacient.obEdMen())
  return f"Pacient: {nom}\nData: {data}\nRisc relatiu: {pacient.obRiscRel()}%\nRisc en un periode de cinc anys: {pacient.obCincAnysRisc()}%"

def obRiscRel(nom, edat, etnia, menarquia, prPart, fPrimGrau, biop, hipAtip, data):
  pacient = ClasseModelGAIL.modelRiscCanMama(edat, etnia, menarquia, prPart, fPrimGrau, biop, hipAtip,data)
  #print(pacient.obEdMen())
  return pacient.obCincAnysRisc()

#Crea una de funció que fa bucle per cada pacient que ha respós l'enquesta.
def obCadaPacient():
  #Obre un document per a escriure les dades.
  f = open("dades.txt","w+")
  f.write("Aquest document recull el risc relatiu i el risc dintre d'un període de cinc anys dels pacients\nque han realitzat l'enquesta. Es considera alt risc en el risc dins del lustre a partir d'1,7%." )
  f.write("\n---------------------------------------------------------------------------------------------")
  fAR = open("pacientsRisc.txt", "w+")
  fAR.write("Aquest document recull pacients que amb alt risc de desenvolupar càncer de mama.")
  fAR.write("\n---------------------------------------------------------------------------------------------")
  #Fa un bucle per totes les columnes excepte la primera, la qual conté les preguntes..
  for x in range(len(valorsDF.index)-1):
    #Recull informació de cada cel·la, i en cas de no haver de ser formatada, pasa de String a int.
    data = valorsDF.iloc[x+1,0]
    nom = valorsDF.iloc[x+1,1]
    edat = int(valorsDF.iloc[x+1,2])
    resEtnia = valorsDF.iloc[x+1,3]
    menarquia = int(valorsDF.iloc[x+1,4])
    resFills = valorsDF.iloc[x+1,5]
    resFam = valorsDF.iloc[x+1,6]
    resBiop = valorsDF.iloc[x+1,7]
    resHipAtip = valorsDF.iloc[x+1,8]

    #Tradueix les respostes que ho requereixen per a la funció del model.
    if resEtnia == "Caucàsica":
      resEtnia = "b"
    else:
      resEtnia = "n"

    if resFills == "No":
      resFills = 0
    elif resFills == "<20":
      resFills = 19
    elif resFills == "20-24":
      resFills = 22
    elif resFills == "25-29":
      resFills = 26
    else:
      resFills = 31

    if resFam == "≥2":
      resFam = 2
    elif resFam == "0":
      resFam = 0
    else:
      resFam = 1

    if resBiop == "≥2":
      resBiop = 2
    elif resBiop == "0":
      resBiop = 0
    else:
      resBiop = 1

    if resHipAtip == "Si" or resHipAtip == "No m'han fet biòpsies.":
      resHipAtip = 1
    elif resHipAtip == "No":
      resHipAtip = 0

    #Afegeig la informació de cada pacient al document.
    f.write("\n" + obDadesFormat(nom, edat, resEtnia, menarquia, resFills, resFam, resBiop, resHipAtip, data))
    f.write("\n---------------------------------------------------------------------------------------------")
    if obRiscRel(nom, edat, resEtnia, menarquia, resFills, resFam, resBiop, resHipAtip, data)>= 1.7:
      fAR.write("\n" + obDadesFormat(nom, edat, resEtnia, menarquia, resFills, resFam, resBiop, resHipAtip, data))
      fAR.write("\n---------------------------------------------------------------------------------------------")

  #Tanca el document
  f.close()
  fAR.close()

obCadaPacient()